name: Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Cache MongoDB binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/mongodb-memory-server
          key: mongodb-binaries-${{ runner.os }}

      - name: Instalar dependencias
        run: npm install

      - name: Correr tests
        run: npm test
